### ISSUE TITLE
鸿蒙flutter3.22.x版本的， 基于flutter_screenutil5.9.3版本构建出的har包，首次访问flutter页面会白屏

### ISSUE THREAD

**Issue by 594723349** [gtbluesky/fusion#10]
DevEco版本：DevEco Studio NEXT Release  5.0.3.900
flutter版本：3.22.0-ohos

鸿蒙flutter3.22.0版本的， flutter_screenutil5.9.3版本构建出的har包，首次访问flutter页面会白屏。
通过flutter run启动鸿蒙项目，首次访问flutter页面不会白屏。

**Comment by gtbluesky** [comment]
正在适配新版本
