### ISSUE TITLE
android,demo工程，白屏问题

### ISSUE THREAD

**Issue by liuyanghh** [gtbluesky/fusion#3]
android,demo工程，
点击“flutter子页面场景”，然后进入页面，点击底部tab1，app切后台，然后app切前台，点击底部tab0，显示白屏

**Comment by gtbluesky** [comment]
没有复现你说的问题

**Comment by liuyanghh** [comment]
> 没有复现你说的问题


https://github.com/gtbluesky/fusion/assets/12457743/0cf1c4e4-0fb1-4933-bb52-edba82f2162b

点击“flutter子页面场景”，然后进入页面，点击底部tab1，app切后台，然后app切前台，点击底部tab0，显示白屏

**Comment by gtbluesky** [comment]
是不是用的3.19？

**Comment by liuyanghh** [comment]
> 是不是用的3.19？

是的

**Comment by gtbluesky** [comment]
3.19中官方代码存在bug，会导致你说的这个问题，预计在下一个版本会修复，所以不要使用3.19这个版本，3.0以上的其他版本都可以
