### ISSUE TITLE
Kotlin 检测方法名重复，无法编译通过

### ISSUE THREAD

**Issue by Virczz** [gtbluesky/fusion#5]
![image](https://github.com/user-attachments/assets/cfec7b8c-5b6f-46e9-b2b1-b323522f9875)

fusion: 4.3.2  kotlin:1.9.0
建议重命名方法

**Comment by gtbluesky** [comment]
kotlin 1.9 不支持方法重载了？

**Comment by Virczz** [comment]
文档没有说。但我前两天清除过build后，现在项目无法编译了。本地修改fusion这两个方法后，可以正常编译。

**Comment by gtbluesky** [comment]
4.4.0已修复
