### ISSUE TITLE
程序运行以后点击”Flutter普通页面场景“问题

### ISSUE THREAD

**Issue by hdf336** [gtbluesky/fusion#7]
程序运行以后点击”Flutter普通页面场景“，有时候会出现点击没有响应情况，断点排查点击事件能够执行，跳转不到flutter页面

**Comment by gtbluesky** [comment]
Android还是iOS？

**Comment by hdf336** [comment]
android出现的

**Comment by gtbluesky** [comment]
使用Activity的context来startActivity
